### ISSUE TITLE
Why is this repo private?

### ISSUE THREAD

**Issue by neanias** [compsoc-edinburgh/website2020#1]
What are you hiding?

**Comment by penalosa** [comment]
I could tell you, but then I'd have to kill you...

**Comment by neanias** [comment]
Seriously though, why is it private?

**Comment by penalosa** [comment]
No clue, I'm afraid - @KyleCotton ?

**Comment by KyleCotton** [comment]
Got to keep all of ComSoc secrets.
*Made Repo Public*
